/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125WorkspaceRouteImport } from './routes/{-$locale}/workspace'
import { Route as Char123LocaleChar125UnauthorizedRouteImport } from './routes/{-$locale}/unauthorized'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125SupportRouteImport } from './routes/{-$locale}/support'
import { Route as Char123LocaleChar125ResetPasswordRouteImport } from './routes/{-$locale}/reset-password'
import { Route as Char123LocaleChar125RegisterRouteImport } from './routes/{-$locale}/register'
import { Route as Char123LocaleChar125ProfileRouteImport } from './routes/{-$locale}/profile'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125MyPageRouteImport } from './routes/{-$locale}/my-page'
import { Route as Char123LocaleChar125LoginRouteImport } from './routes/{-$locale}/login'
import { Route as Char123LocaleChar125ForgotPasswordRouteImport } from './routes/{-$locale}/forgot-password'
import { Route as Char123LocaleChar125FirstTimeSetupRouteImport } from './routes/{-$locale}/first-time-setup'
import { Route as Char123LocaleChar125EducationRouteImport } from './routes/{-$locale}/education'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125ConfirmEmailRouteImport } from './routes/{-$locale}/confirm-email'
import { Route as Char123LocaleChar125CareersRouteImport } from './routes/{-$locale}/careers'
import { Route as Char123LocaleChar125AdminRouteImport } from './routes/{-$locale}/admin'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125TeamIndexRouteImport } from './routes/{-$locale}/team.index'
import { Route as Char123LocaleChar125CaseStudiesIndexRouteImport } from './routes/{-$locale}/case-studies.index'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog.index'
import { Route as Char123LocaleChar125AdminIndexRouteImport } from './routes/{-$locale}/admin/index'
import { Route as Char123LocaleChar125TeamSlugRouteImport } from './routes/{-$locale}/team.$slug'
import { Route as Char123LocaleChar125ServicesIotEdgeComputingRouteImport } from './routes/{-$locale}/services/iot-edge-computing'
import { Route as Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRouteImport } from './routes/{-$locale}/services/enterprise-software-development'
import { Route as Char123LocaleChar125ServicesDigitalTransformationRouteImport } from './routes/{-$locale}/services/digital-transformation'
import { Route as Char123LocaleChar125ServicesDevopsPlatformEngineeringRouteImport } from './routes/{-$locale}/services/devops-platform-engineering'
import { Route as Char123LocaleChar125ServicesCloudArchitectureRouteImport } from './routes/{-$locale}/services/cloud-architecture'
import { Route as Char123LocaleChar125ServicesAiMlBusinessIntelligenceRouteImport } from './routes/{-$locale}/services/ai-ml-business-intelligence'
import { Route as Char123LocaleChar125CaseStudiesIdRouteImport } from './routes/{-$locale}/case-studies.$id'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog.$slug'
import { Route as Char123LocaleChar125AuthCallbackRouteImport } from './routes/{-$locale}/auth.callback'
import { Route as Char123LocaleChar125AdminUsersRouteImport } from './routes/{-$locale}/admin/users'
import { Route as Char123LocaleChar125AdminTagsRouteImport } from './routes/{-$locale}/admin/tags'
import { Route as Char123LocaleChar125AdminRolesRouteImport } from './routes/{-$locale}/admin/roles'
import { Route as Char123LocaleChar125AdminLlmRouteImport } from './routes/{-$locale}/admin/llm'
import { Route as Char123LocaleChar125AdminCategoriesRouteImport } from './routes/{-$locale}/admin/categories'
import { Route as Char123LocaleChar125AdminCaseStudiesRouteImport } from './routes/{-$locale}/admin/case-studies'
import { Route as Char123LocaleChar125AdminBlogRouteImport } from './routes/{-$locale}/admin/blog'
import { Route as Char123LocaleChar125AdminCaseStudiesEditorRouteImport } from './routes/{-$locale}/admin/case-studies_.editor'
import { Route as Char123LocaleChar125AdminBlogEditorRouteImport } from './routes/{-$locale}/admin/blog_.editor'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125WorkspaceRoute =
  Char123LocaleChar125WorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125UnauthorizedRoute =
  Char123LocaleChar125UnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125SupportRoute =
  Char123LocaleChar125SupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ResetPasswordRoute =
  Char123LocaleChar125ResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125RegisterRoute =
  Char123LocaleChar125RegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ProfileRoute =
  Char123LocaleChar125ProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125MyPageRoute =
  Char123LocaleChar125MyPageRouteImport.update({
    id: '/my-page',
    path: '/my-page',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125LoginRoute =
  Char123LocaleChar125LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ForgotPasswordRoute =
  Char123LocaleChar125ForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125FirstTimeSetupRoute =
  Char123LocaleChar125FirstTimeSetupRouteImport.update({
    id: '/first-time-setup',
    path: '/first-time-setup',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125EducationRoute =
  Char123LocaleChar125EducationRouteImport.update({
    id: '/education',
    path: '/education',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ConfirmEmailRoute =
  Char123LocaleChar125ConfirmEmailRouteImport.update({
    id: '/confirm-email',
    path: '/confirm-email',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CareersRoute =
  Char123LocaleChar125CareersRouteImport.update({
    id: '/careers',
    path: '/careers',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminRoute =
  Char123LocaleChar125AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TeamIndexRoute =
  Char123LocaleChar125TeamIndexRouteImport.update({
    id: '/team/',
    path: '/team/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CaseStudiesIndexRoute =
  Char123LocaleChar125CaseStudiesIndexRouteImport.update({
    id: '/case-studies/',
    path: '/case-studies/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminIndexRoute =
  Char123LocaleChar125AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125TeamSlugRoute =
  Char123LocaleChar125TeamSlugRouteImport.update({
    id: '/team/$slug',
    path: '/team/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesIotEdgeComputingRoute =
  Char123LocaleChar125ServicesIotEdgeComputingRouteImport.update({
    id: '/services/iot-edge-computing',
    path: '/services/iot-edge-computing',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute =
  Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRouteImport.update({
    id: '/services/enterprise-software-development',
    path: '/services/enterprise-software-development',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesDigitalTransformationRoute =
  Char123LocaleChar125ServicesDigitalTransformationRouteImport.update({
    id: '/services/digital-transformation',
    path: '/services/digital-transformation',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute =
  Char123LocaleChar125ServicesDevopsPlatformEngineeringRouteImport.update({
    id: '/services/devops-platform-engineering',
    path: '/services/devops-platform-engineering',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesCloudArchitectureRoute =
  Char123LocaleChar125ServicesCloudArchitectureRouteImport.update({
    id: '/services/cloud-architecture',
    path: '/services/cloud-architecture',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute =
  Char123LocaleChar125ServicesAiMlBusinessIntelligenceRouteImport.update({
    id: '/services/ai-ml-business-intelligence',
    path: '/services/ai-ml-business-intelligence',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CaseStudiesIdRoute =
  Char123LocaleChar125CaseStudiesIdRouteImport.update({
    id: '/case-studies/$id',
    path: '/case-studies/$id',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AuthCallbackRoute =
  Char123LocaleChar125AuthCallbackRouteImport.update({
    id: '/auth/callback',
    path: '/auth/callback',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AdminUsersRoute =
  Char123LocaleChar125AdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminTagsRoute =
  Char123LocaleChar125AdminTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminRolesRoute =
  Char123LocaleChar125AdminRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminLlmRoute =
  Char123LocaleChar125AdminLlmRouteImport.update({
    id: '/llm',
    path: '/llm',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCategoriesRoute =
  Char123LocaleChar125AdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCaseStudiesRoute =
  Char123LocaleChar125AdminCaseStudiesRouteImport.update({
    id: '/case-studies',
    path: '/case-studies',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminBlogRoute =
  Char123LocaleChar125AdminBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminCaseStudiesEditorRoute =
  Char123LocaleChar125AdminCaseStudiesEditorRouteImport.update({
    id: '/case-studies_/editor',
    path: '/case-studies/editor',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)
const Char123LocaleChar125AdminBlogEditorRoute =
  Char123LocaleChar125AdminBlogEditorRouteImport.update({
    id: '/blog_/editor',
    path: '/blog/editor',
    getParentRoute: () => Char123LocaleChar125AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteWithChildren
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/confirm-email': typeof Char123LocaleChar125ConfirmEmailRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/education': typeof Char123LocaleChar125EducationRoute
  '/{-$locale}/first-time-setup': typeof Char123LocaleChar125FirstTimeSetupRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/my-page': typeof Char123LocaleChar125MyPageRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/profile': typeof Char123LocaleChar125ProfileRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/support': typeof Char123LocaleChar125SupportRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/unauthorized': typeof Char123LocaleChar125UnauthorizedRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/admin/blog': typeof Char123LocaleChar125AdminBlogRoute
  '/{-$locale}/admin/case-studies': typeof Char123LocaleChar125AdminCaseStudiesRoute
  '/{-$locale}/admin/categories': typeof Char123LocaleChar125AdminCategoriesRoute
  '/{-$locale}/admin/llm': typeof Char123LocaleChar125AdminLlmRoute
  '/{-$locale}/admin/roles': typeof Char123LocaleChar125AdminRolesRoute
  '/{-$locale}/admin/tags': typeof Char123LocaleChar125AdminTagsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/auth/callback': typeof Char123LocaleChar125AuthCallbackRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/case-studies/$id': typeof Char123LocaleChar125CaseStudiesIdRoute
  '/{-$locale}/services/ai-ml-business-intelligence': typeof Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute
  '/{-$locale}/services/cloud-architecture': typeof Char123LocaleChar125ServicesCloudArchitectureRoute
  '/{-$locale}/services/devops-platform-engineering': typeof Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute
  '/{-$locale}/services/digital-transformation': typeof Char123LocaleChar125ServicesDigitalTransformationRoute
  '/{-$locale}/services/enterprise-software-development': typeof Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute
  '/{-$locale}/services/iot-edge-computing': typeof Char123LocaleChar125ServicesIotEdgeComputingRoute
  '/{-$locale}/team/$slug': typeof Char123LocaleChar125TeamSlugRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies/': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/team/': typeof Char123LocaleChar125TeamIndexRoute
  '/{-$locale}/admin/blog/editor': typeof Char123LocaleChar125AdminBlogEditorRoute
  '/{-$locale}/admin/case-studies/editor': typeof Char123LocaleChar125AdminCaseStudiesEditorRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/confirm-email': typeof Char123LocaleChar125ConfirmEmailRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/education': typeof Char123LocaleChar125EducationRoute
  '/{-$locale}/first-time-setup': typeof Char123LocaleChar125FirstTimeSetupRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/my-page': typeof Char123LocaleChar125MyPageRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/profile': typeof Char123LocaleChar125ProfileRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/support': typeof Char123LocaleChar125SupportRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/unauthorized': typeof Char123LocaleChar125UnauthorizedRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/admin/blog': typeof Char123LocaleChar125AdminBlogRoute
  '/{-$locale}/admin/case-studies': typeof Char123LocaleChar125AdminCaseStudiesRoute
  '/{-$locale}/admin/categories': typeof Char123LocaleChar125AdminCategoriesRoute
  '/{-$locale}/admin/llm': typeof Char123LocaleChar125AdminLlmRoute
  '/{-$locale}/admin/roles': typeof Char123LocaleChar125AdminRolesRoute
  '/{-$locale}/admin/tags': typeof Char123LocaleChar125AdminTagsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/auth/callback': typeof Char123LocaleChar125AuthCallbackRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/case-studies/$id': typeof Char123LocaleChar125CaseStudiesIdRoute
  '/{-$locale}/services/ai-ml-business-intelligence': typeof Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute
  '/{-$locale}/services/cloud-architecture': typeof Char123LocaleChar125ServicesCloudArchitectureRoute
  '/{-$locale}/services/devops-platform-engineering': typeof Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute
  '/{-$locale}/services/digital-transformation': typeof Char123LocaleChar125ServicesDigitalTransformationRoute
  '/{-$locale}/services/enterprise-software-development': typeof Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute
  '/{-$locale}/services/iot-edge-computing': typeof Char123LocaleChar125ServicesIotEdgeComputingRoute
  '/{-$locale}/team/$slug': typeof Char123LocaleChar125TeamSlugRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/team': typeof Char123LocaleChar125TeamIndexRoute
  '/{-$locale}/admin/blog/editor': typeof Char123LocaleChar125AdminBlogEditorRoute
  '/{-$locale}/admin/case-studies/editor': typeof Char123LocaleChar125AdminCaseStudiesEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125AdminRouteWithChildren
  '/{-$locale}/careers': typeof Char123LocaleChar125CareersRoute
  '/{-$locale}/confirm-email': typeof Char123LocaleChar125ConfirmEmailRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/education': typeof Char123LocaleChar125EducationRoute
  '/{-$locale}/first-time-setup': typeof Char123LocaleChar125FirstTimeSetupRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125ForgotPasswordRoute
  '/{-$locale}/login': typeof Char123LocaleChar125LoginRoute
  '/{-$locale}/my-page': typeof Char123LocaleChar125MyPageRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/profile': typeof Char123LocaleChar125ProfileRoute
  '/{-$locale}/register': typeof Char123LocaleChar125RegisterRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125ResetPasswordRoute
  '/{-$locale}/support': typeof Char123LocaleChar125SupportRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/unauthorized': typeof Char123LocaleChar125UnauthorizedRoute
  '/{-$locale}/workspace': typeof Char123LocaleChar125WorkspaceRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/admin/blog': typeof Char123LocaleChar125AdminBlogRoute
  '/{-$locale}/admin/case-studies': typeof Char123LocaleChar125AdminCaseStudiesRoute
  '/{-$locale}/admin/categories': typeof Char123LocaleChar125AdminCategoriesRoute
  '/{-$locale}/admin/llm': typeof Char123LocaleChar125AdminLlmRoute
  '/{-$locale}/admin/roles': typeof Char123LocaleChar125AdminRolesRoute
  '/{-$locale}/admin/tags': typeof Char123LocaleChar125AdminTagsRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125AdminUsersRoute
  '/{-$locale}/auth/callback': typeof Char123LocaleChar125AuthCallbackRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/case-studies/$id': typeof Char123LocaleChar125CaseStudiesIdRoute
  '/{-$locale}/services/ai-ml-business-intelligence': typeof Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute
  '/{-$locale}/services/cloud-architecture': typeof Char123LocaleChar125ServicesCloudArchitectureRoute
  '/{-$locale}/services/devops-platform-engineering': typeof Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute
  '/{-$locale}/services/digital-transformation': typeof Char123LocaleChar125ServicesDigitalTransformationRoute
  '/{-$locale}/services/enterprise-software-development': typeof Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute
  '/{-$locale}/services/iot-edge-computing': typeof Char123LocaleChar125ServicesIotEdgeComputingRoute
  '/{-$locale}/team/$slug': typeof Char123LocaleChar125TeamSlugRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125AdminIndexRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
  '/{-$locale}/case-studies/': typeof Char123LocaleChar125CaseStudiesIndexRoute
  '/{-$locale}/team/': typeof Char123LocaleChar125TeamIndexRoute
  '/{-$locale}/admin/blog_/editor': typeof Char123LocaleChar125AdminBlogEditorRoute
  '/{-$locale}/admin/case-studies_/editor': typeof Char123LocaleChar125AdminCaseStudiesEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/careers'
    | '/{-$locale}/confirm-email'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/education'
    | '/{-$locale}/first-time-setup'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/my-page'
    | '/{-$locale}/privacy'
    | '/{-$locale}/profile'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/support'
    | '/{-$locale}/terms'
    | '/{-$locale}/unauthorized'
    | '/{-$locale}/workspace'
    | '/{-$locale}/'
    | '/{-$locale}/admin/blog'
    | '/{-$locale}/admin/case-studies'
    | '/{-$locale}/admin/categories'
    | '/{-$locale}/admin/llm'
    | '/{-$locale}/admin/roles'
    | '/{-$locale}/admin/tags'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/auth/callback'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/case-studies/$id'
    | '/{-$locale}/services/ai-ml-business-intelligence'
    | '/{-$locale}/services/cloud-architecture'
    | '/{-$locale}/services/devops-platform-engineering'
    | '/{-$locale}/services/digital-transformation'
    | '/{-$locale}/services/enterprise-software-development'
    | '/{-$locale}/services/iot-edge-computing'
    | '/{-$locale}/team/$slug'
    | '/{-$locale}/admin/'
    | '/{-$locale}/blog/'
    | '/{-$locale}/case-studies/'
    | '/{-$locale}/team/'
    | '/{-$locale}/admin/blog/editor'
    | '/{-$locale}/admin/case-studies/editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/careers'
    | '/{-$locale}/confirm-email'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/education'
    | '/{-$locale}/first-time-setup'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/my-page'
    | '/{-$locale}/privacy'
    | '/{-$locale}/profile'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/support'
    | '/{-$locale}/terms'
    | '/{-$locale}/unauthorized'
    | '/{-$locale}/workspace'
    | '/{-$locale}'
    | '/{-$locale}/admin/blog'
    | '/{-$locale}/admin/case-studies'
    | '/{-$locale}/admin/categories'
    | '/{-$locale}/admin/llm'
    | '/{-$locale}/admin/roles'
    | '/{-$locale}/admin/tags'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/auth/callback'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/case-studies/$id'
    | '/{-$locale}/services/ai-ml-business-intelligence'
    | '/{-$locale}/services/cloud-architecture'
    | '/{-$locale}/services/devops-platform-engineering'
    | '/{-$locale}/services/digital-transformation'
    | '/{-$locale}/services/enterprise-software-development'
    | '/{-$locale}/services/iot-edge-computing'
    | '/{-$locale}/team/$slug'
    | '/{-$locale}/admin'
    | '/{-$locale}/blog'
    | '/{-$locale}/case-studies'
    | '/{-$locale}/team'
    | '/{-$locale}/admin/blog/editor'
    | '/{-$locale}/admin/case-studies/editor'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/admin'
    | '/{-$locale}/careers'
    | '/{-$locale}/confirm-email'
    | '/{-$locale}/contact'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/education'
    | '/{-$locale}/first-time-setup'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/login'
    | '/{-$locale}/my-page'
    | '/{-$locale}/privacy'
    | '/{-$locale}/profile'
    | '/{-$locale}/register'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/support'
    | '/{-$locale}/terms'
    | '/{-$locale}/unauthorized'
    | '/{-$locale}/workspace'
    | '/{-$locale}/'
    | '/{-$locale}/admin/blog'
    | '/{-$locale}/admin/case-studies'
    | '/{-$locale}/admin/categories'
    | '/{-$locale}/admin/llm'
    | '/{-$locale}/admin/roles'
    | '/{-$locale}/admin/tags'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/auth/callback'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/case-studies/$id'
    | '/{-$locale}/services/ai-ml-business-intelligence'
    | '/{-$locale}/services/cloud-architecture'
    | '/{-$locale}/services/devops-platform-engineering'
    | '/{-$locale}/services/digital-transformation'
    | '/{-$locale}/services/enterprise-software-development'
    | '/{-$locale}/services/iot-edge-computing'
    | '/{-$locale}/team/$slug'
    | '/{-$locale}/admin/'
    | '/{-$locale}/blog/'
    | '/{-$locale}/case-studies/'
    | '/{-$locale}/team/'
    | '/{-$locale}/admin/blog_/editor'
    | '/{-$locale}/admin/case-studies_/editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/workspace': {
      id: '/{-$locale}/workspace'
      path: '/workspace'
      fullPath: '/{-$locale}/workspace'
      preLoaderRoute: typeof Char123LocaleChar125WorkspaceRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/unauthorized': {
      id: '/{-$locale}/unauthorized'
      path: '/unauthorized'
      fullPath: '/{-$locale}/unauthorized'
      preLoaderRoute: typeof Char123LocaleChar125UnauthorizedRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/support': {
      id: '/{-$locale}/support'
      path: '/support'
      fullPath: '/{-$locale}/support'
      preLoaderRoute: typeof Char123LocaleChar125SupportRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/reset-password': {
      id: '/{-$locale}/reset-password'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password'
      preLoaderRoute: typeof Char123LocaleChar125ResetPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/register': {
      id: '/{-$locale}/register'
      path: '/register'
      fullPath: '/{-$locale}/register'
      preLoaderRoute: typeof Char123LocaleChar125RegisterRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/profile': {
      id: '/{-$locale}/profile'
      path: '/profile'
      fullPath: '/{-$locale}/profile'
      preLoaderRoute: typeof Char123LocaleChar125ProfileRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/my-page': {
      id: '/{-$locale}/my-page'
      path: '/my-page'
      fullPath: '/{-$locale}/my-page'
      preLoaderRoute: typeof Char123LocaleChar125MyPageRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/login': {
      id: '/{-$locale}/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125LoginRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/forgot-password': {
      id: '/{-$locale}/forgot-password'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password'
      preLoaderRoute: typeof Char123LocaleChar125ForgotPasswordRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/first-time-setup': {
      id: '/{-$locale}/first-time-setup'
      path: '/first-time-setup'
      fullPath: '/{-$locale}/first-time-setup'
      preLoaderRoute: typeof Char123LocaleChar125FirstTimeSetupRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/education': {
      id: '/{-$locale}/education'
      path: '/education'
      fullPath: '/{-$locale}/education'
      preLoaderRoute: typeof Char123LocaleChar125EducationRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/confirm-email': {
      id: '/{-$locale}/confirm-email'
      path: '/confirm-email'
      fullPath: '/{-$locale}/confirm-email'
      preLoaderRoute: typeof Char123LocaleChar125ConfirmEmailRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/careers': {
      id: '/{-$locale}/careers'
      path: '/careers'
      fullPath: '/{-$locale}/careers'
      preLoaderRoute: typeof Char123LocaleChar125CareersRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin': {
      id: '/{-$locale}/admin'
      path: '/admin'
      fullPath: '/{-$locale}/admin'
      preLoaderRoute: typeof Char123LocaleChar125AdminRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/team/': {
      id: '/{-$locale}/team/'
      path: '/team'
      fullPath: '/{-$locale}/team/'
      preLoaderRoute: typeof Char123LocaleChar125TeamIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/case-studies/': {
      id: '/{-$locale}/case-studies/'
      path: '/case-studies'
      fullPath: '/{-$locale}/case-studies/'
      preLoaderRoute: typeof Char123LocaleChar125CaseStudiesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin/': {
      id: '/{-$locale}/admin/'
      path: '/'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125AdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/team/$slug': {
      id: '/{-$locale}/team/$slug'
      path: '/team/$slug'
      fullPath: '/{-$locale}/team/$slug'
      preLoaderRoute: typeof Char123LocaleChar125TeamSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/iot-edge-computing': {
      id: '/{-$locale}/services/iot-edge-computing'
      path: '/services/iot-edge-computing'
      fullPath: '/{-$locale}/services/iot-edge-computing'
      preLoaderRoute: typeof Char123LocaleChar125ServicesIotEdgeComputingRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/enterprise-software-development': {
      id: '/{-$locale}/services/enterprise-software-development'
      path: '/services/enterprise-software-development'
      fullPath: '/{-$locale}/services/enterprise-software-development'
      preLoaderRoute: typeof Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/digital-transformation': {
      id: '/{-$locale}/services/digital-transformation'
      path: '/services/digital-transformation'
      fullPath: '/{-$locale}/services/digital-transformation'
      preLoaderRoute: typeof Char123LocaleChar125ServicesDigitalTransformationRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/devops-platform-engineering': {
      id: '/{-$locale}/services/devops-platform-engineering'
      path: '/services/devops-platform-engineering'
      fullPath: '/{-$locale}/services/devops-platform-engineering'
      preLoaderRoute: typeof Char123LocaleChar125ServicesDevopsPlatformEngineeringRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/cloud-architecture': {
      id: '/{-$locale}/services/cloud-architecture'
      path: '/services/cloud-architecture'
      fullPath: '/{-$locale}/services/cloud-architecture'
      preLoaderRoute: typeof Char123LocaleChar125ServicesCloudArchitectureRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services/ai-ml-business-intelligence': {
      id: '/{-$locale}/services/ai-ml-business-intelligence'
      path: '/services/ai-ml-business-intelligence'
      fullPath: '/{-$locale}/services/ai-ml-business-intelligence'
      preLoaderRoute: typeof Char123LocaleChar125ServicesAiMlBusinessIntelligenceRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/case-studies/$id': {
      id: '/{-$locale}/case-studies/$id'
      path: '/case-studies/$id'
      fullPath: '/{-$locale}/case-studies/$id'
      preLoaderRoute: typeof Char123LocaleChar125CaseStudiesIdRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/auth/callback': {
      id: '/{-$locale}/auth/callback'
      path: '/auth/callback'
      fullPath: '/{-$locale}/auth/callback'
      preLoaderRoute: typeof Char123LocaleChar125AuthCallbackRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/admin/users': {
      id: '/{-$locale}/admin/users'
      path: '/users'
      fullPath: '/{-$locale}/admin/users'
      preLoaderRoute: typeof Char123LocaleChar125AdminUsersRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/tags': {
      id: '/{-$locale}/admin/tags'
      path: '/tags'
      fullPath: '/{-$locale}/admin/tags'
      preLoaderRoute: typeof Char123LocaleChar125AdminTagsRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/roles': {
      id: '/{-$locale}/admin/roles'
      path: '/roles'
      fullPath: '/{-$locale}/admin/roles'
      preLoaderRoute: typeof Char123LocaleChar125AdminRolesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/llm': {
      id: '/{-$locale}/admin/llm'
      path: '/llm'
      fullPath: '/{-$locale}/admin/llm'
      preLoaderRoute: typeof Char123LocaleChar125AdminLlmRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/categories': {
      id: '/{-$locale}/admin/categories'
      path: '/categories'
      fullPath: '/{-$locale}/admin/categories'
      preLoaderRoute: typeof Char123LocaleChar125AdminCategoriesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/case-studies': {
      id: '/{-$locale}/admin/case-studies'
      path: '/case-studies'
      fullPath: '/{-$locale}/admin/case-studies'
      preLoaderRoute: typeof Char123LocaleChar125AdminCaseStudiesRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/blog': {
      id: '/{-$locale}/admin/blog'
      path: '/blog'
      fullPath: '/{-$locale}/admin/blog'
      preLoaderRoute: typeof Char123LocaleChar125AdminBlogRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/case-studies_/editor': {
      id: '/{-$locale}/admin/case-studies_/editor'
      path: '/case-studies/editor'
      fullPath: '/{-$locale}/admin/case-studies/editor'
      preLoaderRoute: typeof Char123LocaleChar125AdminCaseStudiesEditorRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
    '/{-$locale}/admin/blog_/editor': {
      id: '/{-$locale}/admin/blog_/editor'
      path: '/blog/editor'
      fullPath: '/{-$locale}/admin/blog/editor'
      preLoaderRoute: typeof Char123LocaleChar125AdminBlogEditorRouteImport
      parentRoute: typeof Char123LocaleChar125AdminRoute
    }
  }
}

interface Char123LocaleChar125AdminRouteChildren {
  Char123LocaleChar125AdminBlogRoute: typeof Char123LocaleChar125AdminBlogRoute
  Char123LocaleChar125AdminCaseStudiesRoute: typeof Char123LocaleChar125AdminCaseStudiesRoute
  Char123LocaleChar125AdminCategoriesRoute: typeof Char123LocaleChar125AdminCategoriesRoute
  Char123LocaleChar125AdminLlmRoute: typeof Char123LocaleChar125AdminLlmRoute
  Char123LocaleChar125AdminRolesRoute: typeof Char123LocaleChar125AdminRolesRoute
  Char123LocaleChar125AdminTagsRoute: typeof Char123LocaleChar125AdminTagsRoute
  Char123LocaleChar125AdminUsersRoute: typeof Char123LocaleChar125AdminUsersRoute
  Char123LocaleChar125AdminIndexRoute: typeof Char123LocaleChar125AdminIndexRoute
  Char123LocaleChar125AdminBlogEditorRoute: typeof Char123LocaleChar125AdminBlogEditorRoute
  Char123LocaleChar125AdminCaseStudiesEditorRoute: typeof Char123LocaleChar125AdminCaseStudiesEditorRoute
}

const Char123LocaleChar125AdminRouteChildren: Char123LocaleChar125AdminRouteChildren =
  {
    Char123LocaleChar125AdminBlogRoute: Char123LocaleChar125AdminBlogRoute,
    Char123LocaleChar125AdminCaseStudiesRoute:
      Char123LocaleChar125AdminCaseStudiesRoute,
    Char123LocaleChar125AdminCategoriesRoute:
      Char123LocaleChar125AdminCategoriesRoute,
    Char123LocaleChar125AdminLlmRoute: Char123LocaleChar125AdminLlmRoute,
    Char123LocaleChar125AdminRolesRoute: Char123LocaleChar125AdminRolesRoute,
    Char123LocaleChar125AdminTagsRoute: Char123LocaleChar125AdminTagsRoute,
    Char123LocaleChar125AdminUsersRoute: Char123LocaleChar125AdminUsersRoute,
    Char123LocaleChar125AdminIndexRoute: Char123LocaleChar125AdminIndexRoute,
    Char123LocaleChar125AdminBlogEditorRoute:
      Char123LocaleChar125AdminBlogEditorRoute,
    Char123LocaleChar125AdminCaseStudiesEditorRoute:
      Char123LocaleChar125AdminCaseStudiesEditorRoute,
  }

const Char123LocaleChar125AdminRouteWithChildren =
  Char123LocaleChar125AdminRoute._addFileChildren(
    Char123LocaleChar125AdminRouteChildren,
  )

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125AdminRoute: typeof Char123LocaleChar125AdminRouteWithChildren
  Char123LocaleChar125CareersRoute: typeof Char123LocaleChar125CareersRoute
  Char123LocaleChar125ConfirmEmailRoute: typeof Char123LocaleChar125ConfirmEmailRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125EducationRoute: typeof Char123LocaleChar125EducationRoute
  Char123LocaleChar125FirstTimeSetupRoute: typeof Char123LocaleChar125FirstTimeSetupRoute
  Char123LocaleChar125ForgotPasswordRoute: typeof Char123LocaleChar125ForgotPasswordRoute
  Char123LocaleChar125LoginRoute: typeof Char123LocaleChar125LoginRoute
  Char123LocaleChar125MyPageRoute: typeof Char123LocaleChar125MyPageRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125ProfileRoute: typeof Char123LocaleChar125ProfileRoute
  Char123LocaleChar125RegisterRoute: typeof Char123LocaleChar125RegisterRoute
  Char123LocaleChar125ResetPasswordRoute: typeof Char123LocaleChar125ResetPasswordRoute
  Char123LocaleChar125SupportRoute: typeof Char123LocaleChar125SupportRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125UnauthorizedRoute: typeof Char123LocaleChar125UnauthorizedRoute
  Char123LocaleChar125WorkspaceRoute: typeof Char123LocaleChar125WorkspaceRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125AuthCallbackRoute: typeof Char123LocaleChar125AuthCallbackRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125CaseStudiesIdRoute: typeof Char123LocaleChar125CaseStudiesIdRoute
  Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute: typeof Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute
  Char123LocaleChar125ServicesCloudArchitectureRoute: typeof Char123LocaleChar125ServicesCloudArchitectureRoute
  Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute: typeof Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute
  Char123LocaleChar125ServicesDigitalTransformationRoute: typeof Char123LocaleChar125ServicesDigitalTransformationRoute
  Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute: typeof Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute
  Char123LocaleChar125ServicesIotEdgeComputingRoute: typeof Char123LocaleChar125ServicesIotEdgeComputingRoute
  Char123LocaleChar125TeamSlugRoute: typeof Char123LocaleChar125TeamSlugRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
  Char123LocaleChar125CaseStudiesIndexRoute: typeof Char123LocaleChar125CaseStudiesIndexRoute
  Char123LocaleChar125TeamIndexRoute: typeof Char123LocaleChar125TeamIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
  Char123LocaleChar125404Route: Char123LocaleChar125404Route,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125AdminRoute: Char123LocaleChar125AdminRouteWithChildren,
  Char123LocaleChar125CareersRoute: Char123LocaleChar125CareersRoute,
  Char123LocaleChar125ConfirmEmailRoute: Char123LocaleChar125ConfirmEmailRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125EducationRoute: Char123LocaleChar125EducationRoute,
  Char123LocaleChar125FirstTimeSetupRoute:
    Char123LocaleChar125FirstTimeSetupRoute,
  Char123LocaleChar125ForgotPasswordRoute:
    Char123LocaleChar125ForgotPasswordRoute,
  Char123LocaleChar125LoginRoute: Char123LocaleChar125LoginRoute,
  Char123LocaleChar125MyPageRoute: Char123LocaleChar125MyPageRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125ProfileRoute: Char123LocaleChar125ProfileRoute,
  Char123LocaleChar125RegisterRoute: Char123LocaleChar125RegisterRoute,
  Char123LocaleChar125ResetPasswordRoute:
    Char123LocaleChar125ResetPasswordRoute,
  Char123LocaleChar125SupportRoute: Char123LocaleChar125SupportRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125UnauthorizedRoute: Char123LocaleChar125UnauthorizedRoute,
  Char123LocaleChar125WorkspaceRoute: Char123LocaleChar125WorkspaceRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125AuthCallbackRoute: Char123LocaleChar125AuthCallbackRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125CaseStudiesIdRoute:
    Char123LocaleChar125CaseStudiesIdRoute,
  Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute:
    Char123LocaleChar125ServicesAiMlBusinessIntelligenceRoute,
  Char123LocaleChar125ServicesCloudArchitectureRoute:
    Char123LocaleChar125ServicesCloudArchitectureRoute,
  Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute:
    Char123LocaleChar125ServicesDevopsPlatformEngineeringRoute,
  Char123LocaleChar125ServicesDigitalTransformationRoute:
    Char123LocaleChar125ServicesDigitalTransformationRoute,
  Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute:
    Char123LocaleChar125ServicesEnterpriseSoftwareDevelopmentRoute,
  Char123LocaleChar125ServicesIotEdgeComputingRoute:
    Char123LocaleChar125ServicesIotEdgeComputingRoute,
  Char123LocaleChar125TeamSlugRoute: Char123LocaleChar125TeamSlugRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
  Char123LocaleChar125CaseStudiesIndexRoute:
    Char123LocaleChar125CaseStudiesIndexRoute,
  Char123LocaleChar125TeamIndexRoute: Char123LocaleChar125TeamIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
