/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125TermsRouteImport } from './routes/{-$locale}/terms'
import { Route as Char123LocaleChar125ServicesRouteImport } from './routes/{-$locale}/services'
import { Route as Char123LocaleChar125PrivacyRouteImport } from './routes/{-$locale}/privacy'
import { Route as Char123LocaleChar125GalleryRouteImport } from './routes/{-$locale}/gallery'
import { Route as Char123LocaleChar125FaqRouteImport } from './routes/{-$locale}/faq'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125BlogIndexRouteImport } from './routes/{-$locale}/blog.index'
import { Route as Char123LocaleChar125BlogSlugRouteImport } from './routes/{-$locale}/blog.$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TermsRoute =
  Char123LocaleChar125TermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125ServicesRoute =
  Char123LocaleChar125ServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125PrivacyRoute =
  Char123LocaleChar125PrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125GalleryRoute =
  Char123LocaleChar125GalleryRouteImport.update({
    id: '/gallery',
    path: '/gallery',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125FaqRoute = Char123LocaleChar125FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogIndexRoute =
  Char123LocaleChar125BlogIndexRouteImport.update({
    id: '/blog/',
    path: '/blog/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125BlogSlugRoute =
  Char123LocaleChar125BlogSlugRouteImport.update({
    id: '/blog/$slug',
    path: '/blog/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/faq': typeof Char123LocaleChar125FaqRoute
  '/{-$locale}/gallery': typeof Char123LocaleChar125GalleryRoute
  '/{-$locale}/privacy': typeof Char123LocaleChar125PrivacyRoute
  '/{-$locale}/services': typeof Char123LocaleChar125ServicesRoute
  '/{-$locale}/terms': typeof Char123LocaleChar125TermsRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125BlogSlugRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/gallery'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/gallery'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}/terms'
    | '/{-$locale}'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/faq'
    | '/{-$locale}/gallery'
    | '/{-$locale}/privacy'
    | '/{-$locale}/services'
    | '/{-$locale}/terms'
    | '/{-$locale}/'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/terms': {
      id: '/{-$locale}/terms'
      path: '/terms'
      fullPath: '/{-$locale}/terms'
      preLoaderRoute: typeof Char123LocaleChar125TermsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/services': {
      id: '/{-$locale}/services'
      path: '/services'
      fullPath: '/{-$locale}/services'
      preLoaderRoute: typeof Char123LocaleChar125ServicesRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/privacy': {
      id: '/{-$locale}/privacy'
      path: '/privacy'
      fullPath: '/{-$locale}/privacy'
      preLoaderRoute: typeof Char123LocaleChar125PrivacyRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/gallery': {
      id: '/{-$locale}/gallery'
      path: '/gallery'
      fullPath: '/{-$locale}/gallery'
      preLoaderRoute: typeof Char123LocaleChar125GalleryRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/faq': {
      id: '/{-$locale}/faq'
      path: '/faq'
      fullPath: '/{-$locale}/faq'
      preLoaderRoute: typeof Char123LocaleChar125FaqRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/': {
      id: '/{-$locale}/blog/'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125BlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/blog/$slug': {
      id: '/{-$locale}/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125BlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125FaqRoute: typeof Char123LocaleChar125FaqRoute
  Char123LocaleChar125GalleryRoute: typeof Char123LocaleChar125GalleryRoute
  Char123LocaleChar125PrivacyRoute: typeof Char123LocaleChar125PrivacyRoute
  Char123LocaleChar125ServicesRoute: typeof Char123LocaleChar125ServicesRoute
  Char123LocaleChar125TermsRoute: typeof Char123LocaleChar125TermsRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125BlogSlugRoute: typeof Char123LocaleChar125BlogSlugRoute
  Char123LocaleChar125BlogIndexRoute: typeof Char123LocaleChar125BlogIndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
  Char123LocaleChar125404Route: Char123LocaleChar125404Route,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125FaqRoute: Char123LocaleChar125FaqRoute,
  Char123LocaleChar125GalleryRoute: Char123LocaleChar125GalleryRoute,
  Char123LocaleChar125PrivacyRoute: Char123LocaleChar125PrivacyRoute,
  Char123LocaleChar125ServicesRoute: Char123LocaleChar125ServicesRoute,
  Char123LocaleChar125TermsRoute: Char123LocaleChar125TermsRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125BlogSlugRoute: Char123LocaleChar125BlogSlugRoute,
  Char123LocaleChar125BlogIndexRoute: Char123LocaleChar125BlogIndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
